language: bash
dist: bionic

stages:
  - lint

if: branch = master OR type = pull_request

jobs:
  include:
    - stage: lint
      name: Project Syntax Verification
      script: make docker/run target=lint
