---
version: 0.2

phases:
  install:
    commands:
      - git clone https://github.com/plus3it/terraform-bootstrap.git && chmod +x terraform-bootstrap/install.sh
      - terraform-bootstrap/install.sh
  pre_build:
    commands:
      - export TF_VAR_tfi_codebuild_id="${CODEBUILD_BUILD_ID}"
      - terraform init -no-color -input=false                                 # init terraform
      - terraform plan -no-color -out=tfplan -input=false                     # plan terraform
  build:
    commands:
      - terraform apply -no-color -input=false tfplan                         # apply terraform
  post_build:
    commands:
      - ARTIFACT_PATH="${TF_VAR_tfi_s3_bucket}/$(terraform output build_date_ymd)/$(terraform output build_date_hm)_$(terraform output build_id)"
      - echo "ARTIFACT_LOCATION=https://s3.console.aws.amazon.com/s3/buckets/${ARTIFACT_PATH}/"
      - terraform output -no-color | aws s3 cp - "s3://${ARTIFACT_PATH}/terraform_output.log" || true
      - test -r $TF_LOG_PATH && aws s3 cp $TF_LOG_PATH "s3://${ARTIFACT_PATH}/terraform.log" || true
      - test -r terraform.tfstate && aws s3 cp terraform.tfstate "s3://${ARTIFACT_PATH}/terraform.tfstate" || true
      - |
        if [ "${TF_DESTROY_AFTER_TEST}" = "true" ]; then                       # destroy resources
          terraform destroy -no-color -input=false -force
        fi
