---
version: 0.2

env:
  variables:
    TFI_DESC_URL:           https://github.com/YakDriver/terrafirm
    TFI_TF_ZIP:             https://releases.hashicorp.com/terraform/0.11.2/terraform_0.11.2_linux_amd64.zip
    TFI_JQ_INSTALL:         https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
    TFI_WIN_SECURITY_GRP:   "terrafirm_winrm_sg"                                   #ephemeral name for sg
    TFI_LX_SECURITY_GRP:    "terrafirm_ssh_sg"                                     #ephemeral name for sg
    TFI_KEY_PAIR_NAME:      "svc_terrafirm2"                                       #ephemeral name for keypair
    # Below here are variables that can (and likely are) overwritten from the AWS CodeBuild project
    # Values in CodeBuild take precedence so LEAVE ALL OF THESE HERE even if defining there
    TFI_SUBNET_ID:          ""                                                     #optional in CodeBuild
    TFI_BUILD_WIN:          "all"                                                  #optional in CodeBuild
    TFI_BUILD_LX:           "all"                                                  #optional in CodeBuild
    TFI_PS_PRIVATE_KEY:     "/path/to/parameter/store"                             #REQUIRED in CodeBuild
    TFI_PS_PUBLIC_KEY:      "/path/to/parameter/store"                             #REQUIRED in CodeBuild
    TFI_PS_PASSWD_KEY:      "/path/to/parameter/store"                             #REQUIRED in CodeBuild
    TFI_RM_USER:            "Administrator"                                        #optional in CodeBuild
    TFI_SSH_USER:           "root"                                                 #optional in CodeBuild
    TFI_INSTANCE_PROFILE:   ""                                                     #optional in CodeBuild
    TFI_ASSIGN_PUBLIC_IP:   "false"                                                #optional in CodeBuild
    TFI_WIN_INSTANCE_TYPE:  "t2.medium"                                            #optional in CodeBuild
    TFI_LX_INSTANCE_TYPE:   "t2.micro"                                             #optional in CodeBuild
    TFI_REPO:               "https://github.com/plus3it/watchmaker.git"            #optional in CodeBuild
    TFI_BRANCH:             "master"                                               #optional in CodeBuild
    TFI_COMMON_ARGS:        "-n --log-level debug"                                 #optional in CodeBuild
    TFI_WIN_ARGS:           "--log-dir=C:\\Watchmaker\\Logs"                       #optional in CodeBuild
    TFI_LX_ARGS:            "--log-dir=/var/log/watchmaker"                        #optional in CodeBuild
    TFI_WIN_USERDATA_LOG:   "C:\\Temp\\userdata.log"
    TFI_LX_USERDATA_LOG:    "/tmp/userdata.log"
    TFI_DESTROY_AFTER_TEST: "true"                                                 #optional in CodeBuild

phases:
  install:
    commands:
      - echo "Installing unzip............"
      - apt -y install unzip
      - echo "Installing jq..............."
      - curl -L "${TFI_JQ_INSTALL}" -o jq.dms && chmod +x jq.dms
      - ./jq.dms --version
      - echo "Installing Terraform..."
      - echo `pwd`
      - curl -L "${TFI_TF_ZIP}" -o tf.zip && unzip tf.zip
  pre_build:
    commands:
      - #-------------------------------------------------------------------------------------------------
      - echo "Terraform version " ; ./terraform --version
      - #-------------------------------------------------------------------------------------------------
      - echo "SETUP - Simple Env Vars......................................................."
      - aws configure set region "${AWS_REGION}"
      - TF_VAR_tfi_region="${AWS_REGION}" ; export TF_VAR_tfi_region
      - TF_VAR_tfi_win_security_grp="${TFI_WIN_SECURITY_GRP}" ; export TF_VAR_tfi_win_security_grp
      - TF_VAR_tfi_lx_security_grp="${TFI_LX_SECURITY_GRP}" ; export TF_VAR_tfi_lx_security_grp     
      - TF_VAR_tfi_key_pair_name="${TFI_KEY_PAIR_NAME}" ; export TF_VAR_tfi_key_pair_name
      - TF_VAR_tfi_cb_ip="$(curl http://checkip.amazonaws.com)" ; export TF_VAR_tfi_cb_ip # IP of CodeBuild instance for use by security group, so only open to one machine
      - TF_VAR_tfi_build_win="${TFI_BUILD_WIN}" ; export TF_VAR_tfi_build_win
      - TF_VAR_tfi_build_lx="${TFI_BUILD_LX}" ; export TF_VAR_tfi_build_lx
      - TF_VAR_tfi_private_key="$(aws ssm get-parameters --name ${TFI_PS_PRIVATE_KEY} --with-decryption --query 'Parameters[0].Value' --out text)" ; export TF_VAR_tfi_private_key
      - TF_VAR_tfi_public_key="$(aws ssm get-parameters --name ${TFI_PS_PUBLIC_KEY} --with-decryption --query 'Parameters[0].Value' --out text)" ; export TF_VAR_tfi_public_key
      - TF_VAR_tfi_rm_pass="$(aws ssm get-parameters --name ${TFI_PS_PASSWD_KEY} --with-decryption --query 'Parameters[0].Value' --out text)" ; export TF_VAR_tfi_rm_pass
      - TF_VAR_tfi_rm_user="${TFI_RM_USER}" ; export TF_VAR_tfi_rm_user      
      - TF_VAR_tfi_ssh_user="${TFI_SSH_USER}" ; export TF_VAR_tfi_ssh_user
      - TF_VAR_tfi_instance_profile="${TFI_INSTANCE_PROFILE}" ; export TF_VAR_tfi_instance_profile
      - TF_VAR_tfi_assign_public_ip="${TFI_ASSIGN_PUBLIC_IP}" ; export TF_VAR_tfi_assign_public_ip
      - TF_VAR_tfi_win_instance_type="${TFI_WIN_INSTANCE_TYPE}" ; export TF_VAR_tfi_win_instance_type
      - TF_VAR_tfi_lx_instance_type="${TFI_LX_INSTANCE_TYPE}" ; export TF_VAR_tfi_lx_instance_type
      - TF_VAR_tfi_repo="${TFI_REPO}" ; export TF_VAR_tfi_repo
      - TF_VAR_tfi_branch="${TFI_BRANCH}" ; export TF_VAR_tfi_branch
      - TF_VAR_tfi_common_args="${TFI_COMMON_ARGS}" ; export TF_VAR_tfi_common_args
      - TF_VAR_tfi_win_args="${TFI_WIN_ARGS}" ; export TF_VAR_tfi_win_args
      - TF_VAR_tfi_lx_args="${TFI_LX_ARGS}" ; export TF_VAR_tfi_lx_args
      - TF_VAR_tfi_win_userdata_log="${TFI_USERDATA_LOG}" ; export TF_VAR_tfi_win_userdata_log
      - TF_VAR_tfi_lx_userdata_log="${TFI_USERDATA_LOG}" ; export TF_VAR_tfi_lx_userdata_log
      - #-------------------------------------------------------------------------------------------------
      - echo "SETUP - Validate subnet, find VPC.........................................................."
      - # If subnet id is valid, finds the associated VPC and assigns variables. Otherwise, blanks (defaults)
      - TF_VAR_tfi_subnet_id=""
      - TF_VAR_tfi_vpc_id=""
      - |
        if [ -n "${TFI_SUBNET_ID}" ] ; then
          TFI_VPC_ID="$(aws ec2 describe-subnets --filters "Name=subnet-id,Values=${TFI_SUBNET_ID}" | ./jq.dms -r '.Subnets[0].VpcId')"
          if [ "${TFI_VPC_ID}" != "null" ] && [ -n "${TFI_VPC_ID}" ] ; then
            TF_VAR_tfi_subnet_id="${TFI_SUBNET_ID}"
            TF_VAR_tfi_vpc_id="${TFI_VPC_ID}"
          fi
        fi
      - export TF_VAR_tfi_subnet_id ; export TF_VAR_tfi_vpc_id
      - #-------------------------------------------------------------------------------------------------
      - echo "SETUP - Create key pair if necessary......................................................."      
      - |
        if aws ec2 describe-key-pairs --key-name "${TFI_KEY_PAIR_NAME}" ; then
          echo "Key pair already exists..."
        else
          echo "Creating a key pair "
          aws ec2 import-key-pair --key-name "${TFI_KEY_PAIR_NAME}" --public-key-material "${TF_VAR_tfi_public_key}"
        fi
      - #-------------------------------------------------------------------------------------------------
      - echo "SETUP - Delete duplicate security groups..................................................."
      - # names to be used when creating security groups
      - TFI_LX_SG_ID="$(aws ec2 describe-security-groups --filters Name=group-name,Values=${TFI_LX_SECURITY_GRP} | ./jq.dms -r '.SecurityGroups[0].GroupId')"
      - |
        if [ "${TFI_LX_SG_ID}" != "null" ] && [ -n "${TFI_LX_SG_ID}" ] ; then
          aws ec2 delete-security-group --group-id "${TFI_LX_SG_ID}"
        fi
      - TFI_WIN_SG_ID="$(aws ec2 describe-security-groups --filters Name=group-name,Values=${TFI_WIN_SECURITY_GRP} | ./jq.dms -r '.SecurityGroups[0].GroupId')"
      - |
        if [ "${TFI_WIN_SG_ID}" != "null" ] && [ -n "${TFI_WIN_SG_ID}" ] ; then
          aws ec2 delete-security-group --group-id "${TFI_WIN_SG_ID}"
        fi        
      - #-------------------------------------------------------------------------------------------------
      - echo "SETUP - Assemble userdata files............................................................"   
      - sed -i -e '/WATCHMAKER_INSTALL_GOES_HERE/{r windows/install_watchmaker.ps1' -e 'd}' windows/userdata.ps1
      - sed -i -e '/WATCHMAKER_INSTALL_GOES_HERE/{r linux/install_watchmaker.sh' -e 'd}' linux/userdata.sh
      - #-------------------------------------------------------------------------------------------------  
      - echo "SETUP - Complete, init Terraform..........................................................."         
      - echo "Initializing Terraform " ; ./terraform init -input=false
      - echo "Importing key pair " ; ./terraform import aws_key_pair.auth "${TFI_KEY_PAIR_NAME}"
      - echo "Create provisiong plan " ; ./terraform plan -out=tfplan -input=false
  build:
    commands:
      - echo "Apply Terraform..........................................................................." 
      - ./terraform apply -input=false tfplan
  post_build:
    commands:
      - |
        if [ "${TFI_DESTROY_AFTER_TEST}" = "true" ]; then
          echo "Destroying Terraform-created resources (e.g., security groups, instances, key pair)..."
          ./terraform destroy -input=false -force
          if aws ec2 describe-key-pairs --key-name "${TFI_KEY_PAIR_NAME}" ; then
            echo "Deleting key pair..."
            aws ec2 delete-key-pair --key-name "${TFI_KEY_PAIR_NAME}"
          fi
        else
          echo "********* WARNING *********"
          echo "NOT destroying resources!"
          echo "Expensive AWS resources are still up and running and need to be terminated/deleted manually."
          echo "***************************"
        fi
      - echo "Terrafirm completed on $(date)"
artifacts:
  files:
    - '/tmp/userdata.log'
    - 'C:\\Temp\\userdata.log'
  discard-paths: yes
